cloudant.username=apikey-v2-1scjskvl05tzmq5aqk5fq108wa1gyt0ncjighz3kkky3
cloudant.password=e1ead77ca4b5855104200bbda063dfbc
cloudant.url=https://apikey-v2-1scjskvl05tzmq5aqk5fq108wa1gyt0ncjighz3kkky3:e1ead77ca4b5855104200bbda063dfbc@a2bd6471-18ef-4943-8111-09b1e08db544-bluemix.cloudantnosqldb.appdomain.cloud
cloudant.db=terrell-benefits-api

kafka.bootstrapAddress=localhost:9092
benefit.topic.name=benefit-topic
